/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionBD;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import vista.*;

/**
 *
 * @author Garci
 */
public class ListaStock3 extends javax.swing.JFrame {

    /**
     *
     * Creates new form ListaStock
     */
  

    VistaOrdenesPorLLamadasVentana1 vistaCall;

    public ListaStock3() {
        initComponents();
        consultarDatos();
        this.setLocation(100, 100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusquedaStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTA STOCK");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("CONSULTA DE PRODUCTO"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProductos3 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableProductos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CANTIDAD", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos3.getTableHeader().setReorderingAllowed(false);
        jTableProductos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductos3MouseClicked(evt);
            }
        });
        jTableProductos3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableProductos3KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProductos3);
        if (jTableProductos3.getColumnModel().getColumnCount() > 0) {
            jTableProductos3.getColumnModel().getColumn(0).setResizable(false);
            jTableProductos3.getColumnModel().getColumn(1).setResizable(false);
            jTableProductos3.getColumnModel().getColumn(2).setResizable(false);
            jTableProductos3.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 600, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LISTA STOCK");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setText("BUSCAR PRODUCTOS:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtBusquedaStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaStockKeyReleased(evt);
            }
        });
        jPanel3.add(txtBusquedaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 460, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductos3MouseClicked
        // TODO add your handling code here:
        int fila = jTableProductos3.getSelectedRow();
        int seleccionar = jTableProductos3.rowAtPoint(evt.getPoint());
        float cantivalidar = Float.parseFloat(jTableProductos3.getValueAt(seleccionar, 2).toString());

        if (cantivalidar == 0.0) {
            JOptionPane.showMessageDialog(null, "NO HAY CANTIDADES EN EXISTENCIA X_X ", "Mensaje", JOptionPane.WARNING_MESSAGE);
        } else {

            vistaCall.txtIdentificadorProduct.setText(String.valueOf(jTableProductos3.getValueAt(seleccionar, 0)));
            vistaCall.txtNombreProducto.setText(String.valueOf(jTableProductos3.getValueAt(seleccionar, 1)));
            vistaCall.txtStock.setText(String.valueOf(jTableProductos3.getValueAt(seleccionar, 2)));
            vistaCall.txtPrecio.setText(String.valueOf(jTableProductos3.getValueAt(seleccionar, 3)));

        }

    }//GEN-LAST:event_jTableProductos3MouseClicked

    private void jTableProductos3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProductos3KeyPressed
          ConexionBD conec = new ConexionBD();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {;
            this.setVisible(false);
            conec.cerrarConexion();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProductos3KeyPressed

    private void txtBusquedaStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaStockKeyReleased

        String buscar = txtBusquedaStock.getText().toUpperCase();

        BusquedaFiltrada(buscar);


    }//GEN-LAST:event_txtBusquedaStockKeyReleased

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaStock3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaStock3().setVisible(true);
            }
        });
    }

    private void consultarDatos() {
        ConexionBD objCBD = new ConexionBD();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO");
        jTableProductos3.setModel(modelo);

        String[] datos = new String[4];

        
        objCBD.realizarConexion();
        ArrayList instruccionBD = new ArrayList();
        instruccionBD.add("{call sp_ConsultarProductosTable2()}");
        ResultSet cdr = objCBD.ejecutarConsulta(instruccionBD);
        try {
            while (cdr.next()) {
                datos[0] = cdr.getString(1);
                datos[1] = cdr.getString(2);
                datos[2] = cdr.getString(3);
                datos[3] = cdr.getString(4);

                modelo.addRow(datos);

            }
            jTableProductos3.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la consulta" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);

        }finally {

            objCBD.cerrarConexion();
        }

    }

    private void BusquedaFiltrada(String productoStock) {
         ConexionBD objCBD = new ConexionBD();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO");

        jTableProductos3.setModel(modelo);
        String[] datos = new String[4];
       
        objCBD.realizarConexion();
        ArrayList instruccionBD = new ArrayList();
        instruccionBD.add("{call sp_ConsultarStoock(?)}");
        instruccionBD.add(productoStock);
        ResultSet cdr = objCBD.ejecutarConsulta(instruccionBD);
        try {
            while (cdr.next()) {
                datos[0] = cdr.getString("id_producto");
                datos[1] = cdr.getString("nombre_producto");
                datos[2] = cdr.getString("cantidad");
                datos[3] = cdr.getString("precio_venta");

                modelo.addRow(datos);
            }
            jTableProductos3.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la consulta" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
       }finally {

            objCBD.cerrarConexion();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableProductos3;
    private javax.swing.JTextField txtBusquedaStock;
    // End of variables declaration//GEN-END:variables
}
