/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author José Manuel
 */
public class VistaAcceso extends javax.swing.JFrame {
String usuarioo;
String password;
    /**
     * Creates new form VistaAcceso
     */
    public VistaAcceso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        lblIniciarSesión = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pwfPassword = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        pPrincipal.setBackground(new java.awt.Color(0, 153, 153));
        pPrincipal.setForeground(new java.awt.Color(51, 0, 255));
        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User.png"))); // NOI18N
        pPrincipal.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 250, 250));

        lblIniciarSesión.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblIniciarSesión.setText("Inicio de Sesión");
        pPrincipal.add(lblIniciarSesión, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, 40));

        lblUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        lblUsuario.setText("Usuario:");
        pPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, -1));

        lblPassword.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 36)); // NOI18N
        lblPassword.setText("Password:");
        pPrincipal.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, -1));

        txtUsuario.setName("txtUsuario"); // NOI18N
        pPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 40));

        pwfPassword.setName("pwfPassword"); // NOI18N
        pPrincipal.add(pwfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 160, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCancelar2.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        pPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 160, 50));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log on1.jpg"))); // NOI18N
        btnIngresar.setText("Ingresar");
        pPrincipal.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JLabel lblIniciarSesión;
    public javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JPanel pPrincipal;
    public static javax.swing.JPasswordField pwfPassword;
    public static javax.swing.JTextField txtUsuario;
    public javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

}
