/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAcceso;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.ModeloAcceso;
import conexion.ConexionBD;

/**
 *
 * @author José Manuel
 */
public class VistaPrincipal extends javax.swing.JFrame {

    VistaAcceso van;
   

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mniProductos = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        mniEmpelados = new javax.swing.JMenuItem();
        mnuOrdenes = new javax.swing.JMenu();
        mniOrdenesPresenciales = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mniVentasLlamada = new javax.swing.JMenuItem();
        mnuHorarios = new javax.swing.JMenu();
        mniConsultarHorarios = new javax.swing.JMenuItem();
        mnuVentaDelDia = new javax.swing.JMenu();
        mniVentasCall = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mniConsultas = new javax.swing.JMenuItem();
        mnuRepartidor = new javax.swing.JMenu();
        mniRepartidores = new javax.swing.JMenuItem();
        mnuLocalidad = new javax.swing.JMenu();
        mniLocalidades = new javax.swing.JMenuItem();
        mnuAcercaDe = new javax.swing.JMenu();
        mniAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista Principal");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unas montañas6.jpg"))); // NOI18N

        dpEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1934, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        barraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compu.png"))); // NOI18N
        mnuArchivo.setText("Archivo");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mniSalir);

        barraMenu.add(mnuArchivo);

        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.jpg"))); // NOI18N
        mnuProductos.setText("Productos");

        mniProductos.setText("Gestionar Productos");
        mniProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProductosActionPerformed(evt);
            }
        });
        mnuProductos.add(mniProductos);

        barraMenu.add(mnuProductos);

        mnuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/customers.jpg"))); // NOI18N
        mnuEmpleados.setText("Empleados");

        mniEmpelados.setText("Gestionar Empleados");
        mniEmpelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpeladosActionPerformed(evt);
            }
        });
        mnuEmpleados.add(mniEmpelados);

        barraMenu.add(mnuEmpleados);

        mnuOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenes2.jpg"))); // NOI18N
        mnuOrdenes.setText("Ordenes");

        mniOrdenesPresenciales.setText("Tomar orden por llamada V1");
        mniOrdenesPresenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOrdenesPresencialesActionPerformed(evt);
            }
        });
        mnuOrdenes.add(mniOrdenesPresenciales);

        barraMenu.add(mnuOrdenes);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        mniVentasLlamada.setText("Consultar Ventas Generales");
        mniVentasLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentasLlamadaActionPerformed(evt);
            }
        });
        mnuVentas.add(mniVentasLlamada);

        barraMenu.add(mnuVentas);

        mnuHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horario.png"))); // NOI18N
        mnuHorarios.setText("Horarios");

        mniConsultarHorarios.setText("Consultar Horarios");
        mniConsultarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultarHorariosActionPerformed(evt);
            }
        });
        mnuHorarios.add(mniConsultarHorarios);

        barraMenu.add(mnuHorarios);

        mnuVentaDelDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/incrementoVentas1.png"))); // NOI18N
        mnuVentaDelDia.setText("Ventas Del Dia ");

        mniVentasCall.setText("Ventas Generales");
        mniVentasCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentasCallActionPerformed(evt);
            }
        });
        mnuVentaDelDia.add(mniVentasCall);

        jMenuItem1.setText("Visualizar Bítacora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuVentaDelDia.add(jMenuItem1);

        barraMenu.add(mnuVentaDelDia);

        mnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verVentas1.jpg"))); // NOI18N
        mnuConsultas.setText("Consulta de ventas");

        mniConsultas.setText("Consultar Ventas Generales");
        mniConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultasActionPerformed(evt);
            }
        });
        mnuConsultas.add(mniConsultas);

        barraMenu.add(mnuConsultas);

        mnuRepartidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repas.png"))); // NOI18N
        mnuRepartidor.setText(" Repartidores");

        mniRepartidores.setText("Géstion Repartidor");
        mniRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRepartidoresActionPerformed(evt);
            }
        });
        mnuRepartidor.add(mniRepartidores);

        barraMenu.add(mnuRepartidor);

        mnuLocalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loclaidad.png"))); // NOI18N
        mnuLocalidad.setText("Localidades");

        mniLocalidades.setText("Géstion Localidades");
        mniLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLocalidadesActionPerformed(evt);
            }
        });
        mnuLocalidad.add(mniLocalidades);

        barraMenu.add(mnuLocalidad);

        mnuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenador-portatil1.png"))); // NOI18N
        mnuAcercaDe.setText("Información del Sistema");

        mniAcerca.setText("Acerca Del Sistema");
        mniAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAcercaActionPerformed(evt);
            }
        });
        mnuAcercaDe.add(mniAcerca);

        barraMenu.add(mnuAcercaDe);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProductosActionPerformed
        //

    }//GEN-LAST:event_mniProductosActionPerformed

    private void mniConsultarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultarHorariosActionPerformed
        abrirVistaHorario();

    }//GEN-LAST:event_mniConsultarHorariosActionPerformed

    private void mniOrdenesPresencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOrdenesPresencialesActionPerformed
        abrirVistaOrdenesPorLlamadaV1();
    }//GEN-LAST:event_mniOrdenesPresencialesActionPerformed

    private void mniVentasLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentasLlamadaActionPerformed
        // TODO add your handling code here:
        mostrarVentasPorLLamada();
    }//GEN-LAST:event_mniVentasLlamadaActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
       ConexionBD conec = new ConexionBD();
        int r = JOptionPane.showConfirmDialog(null, "¿Estás seguro de salir?",
                "Salir", JOptionPane.YES_NO_OPTION);

        if (r == 0) {

            VistaAcceso vA = new VistaAcceso();
            ModeloAcceso mA = new ModeloAcceso();
            ControladorAcceso cA = new ControladorAcceso(vA, mA);
            vA.setVisible(true);
            vA.show();
            dispose();
            conec.cerrarConexion();

        }


    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultasActionPerformed
        consultarVentasLLamdas();

    }//GEN-LAST:event_mniConsultasActionPerformed

    private void mniVentasCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentasCallActionPerformed
        openVentasPorLLamadas();
    }//GEN-LAST:event_mniVentasCallActionPerformed

    private void mniRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRepartidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniRepartidoresActionPerformed

    private void mniLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLocalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniLocalidadesActionPerformed

    private void mniAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAcercaActionPerformed
        abrirAcercaDelSistema();        // TODO add your handling code here:
    }//GEN-LAST:event_mniAcercaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abrirMiBitacora();  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mniEmpeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpeladosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniEmpeladosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar barraMenu;
    public static javax.swing.JDesktopPane dpEscritorio;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem mniAcerca;
    public javax.swing.JMenuItem mniConsultarHorarios;
    public javax.swing.JMenuItem mniConsultas;
    public javax.swing.JMenuItem mniEmpelados;
    public javax.swing.JMenuItem mniLocalidades;
    public javax.swing.JMenuItem mniOrdenesPresenciales;
    public javax.swing.JMenuItem mniProductos;
    public javax.swing.JMenuItem mniRepartidores;
    public javax.swing.JMenuItem mniSalir;
    public javax.swing.JMenuItem mniVentasCall;
    private javax.swing.JMenuItem mniVentasLlamada;
    public javax.swing.JMenu mnuAcercaDe;
    public javax.swing.JMenu mnuArchivo;
    public javax.swing.JMenu mnuConsultas;
    public javax.swing.JMenu mnuEmpleados;
    public javax.swing.JMenu mnuHorarios;
    public javax.swing.JMenu mnuLocalidad;
    public javax.swing.JMenu mnuOrdenes;
    public javax.swing.JMenu mnuProductos;
    public javax.swing.JMenu mnuRepartidor;
    public javax.swing.JMenu mnuVentaDelDia;
    public javax.swing.JMenu mnuVentas;
    // End of variables declaration//GEN-END:variables

    private void abrirVistaHorario() {

        VistaHorario h = new VistaHorario();
        dpEscritorio.add(h);
        h.show();
    }

    private void abrirVistaOrdenesPorLlamadaV1() {

        VistaOrdenesPorLLamadasVentana1 p = new VistaOrdenesPorLLamadasVentana1();
        dpEscritorio.add(p);
        p.show();

    }

  

    private void mostrarVentasPorLLamada() {

        VistaDetalleOrdenLlamadas ventas = new VistaDetalleOrdenLlamadas();
        dpEscritorio.add(ventas);
        ventas.show();

    }

    private void openVentasPorLLamadas() {
        AsiganarRepartidoresLLamadas ventasCall = new AsiganarRepartidoresLLamadas();
        dpEscritorio.add(ventasCall);
        ventasCall.show();
    }

    private void consultarVentasLLamdas() {

        ConsultarRepartidoresLLamadas12 consultarVentasCall = new ConsultarRepartidoresLLamadas12();
        dpEscritorio.add(consultarVentasCall);
        consultarVentasCall.show();

    }

    private void abrirAcercaDelSistema() {
        InformacionDelSistema about = new InformacionDelSistema();
        dpEscritorio.add(about);
        about.show();

    }

    private void abrirMiBitacora() {
        VistaDeOrdenesRealizadas bitacora = new VistaDeOrdenesRealizadas();
        dpEscritorio.add(bitacora);
        bitacora.show();
        
    }

    

   

}
