/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vista.ListaClientesLlamada1.TablaClientes5;

/**
 *
 * @author Garci
 */
public class VistaDeOrdenesRealizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDeOrdenesRealizadas
     */
    public VistaDeOrdenesRealizadas() {
        initComponents();
        visualizarMiBitacoraGeneral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMiBitacora = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filtroPorBitacora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ORDENES REALIZADAS ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMiBitacora = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableMiBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUM. ORDEN", "NOMBRE CLIENTE", "NOMBRE PRODUCTO", "CANTIDAD ", "PRECIO ORDEN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMiBitacora.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMiBitacora);
        if (jTableMiBitacora.getColumnModel().getColumnCount() > 0) {
            jTableMiBitacora.getColumnModel().getColumn(0).setResizable(false);
            jTableMiBitacora.getColumnModel().getColumn(1).setResizable(false);
            jTableMiBitacora.getColumnModel().getColumn(2).setResizable(false);
            jTableMiBitacora.getColumnModel().getColumn(3).setResizable(false);
            jTableMiBitacora.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BÍTACORA DE ORDENES REALIZADAS");

        jLabel2.setText("BUSQUEDA POR NOMBRE  DE CLIENTE:");

        filtroPorBitacora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroPorBitacoraKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/898989898989.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(filtroPorBitacora)))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addGap(162, 162, 162))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(filtroPorBitacora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroPorBitacoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroPorBitacoraKeyReleased
        String buscar = filtroPorBitacora.getText().toUpperCase();

        BusquedaFiltrada(buscar);

    }//GEN-LAST:event_filtroPorBitacoraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filtroPorBitacora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableMiBitacora;
    // End of variables declaration//GEN-END:variables

    private void visualizarMiBitacoraGeneral() {
        ConexionBD objCBD = new ConexionBD();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NUM. ORDEN");
        modelo.addColumn("NOMBRE CLIENTE");
        modelo.addColumn("NOMBRE PRODUCTO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO ORDEN");

        jTableMiBitacora.setModel(modelo);
        String[] datos = new String[5];

        objCBD.realizarConexion();
        ArrayList instruccionBD = new ArrayList();
        instruccionBD.add("{call sp_consultarBitacora90()}");
        ResultSet cdr = objCBD.ejecutarConsulta(instruccionBD);
        try {
            while (cdr.next()) {
                datos[0] = cdr.getString("id_ordenC");
                datos[1] = cdr.getString("nombre_cliente_llamada");
                datos[2] = cdr.getString("nombreP");
                datos[3] = cdr.getString("cantidad");
                datos[4] = cdr.getString("precioOrden");

                modelo.addRow(datos);
            }
            jTableMiBitacora.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la consulta" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);

        } finally {

            objCBD.cerrarConexion();
        }
    }

    private void BusquedaFiltrada(String texto) {
        ConexionBD objCBD = new ConexionBD();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NUM. ORDEN");
        modelo.addColumn("NOMBRE CLIENTE");
        modelo.addColumn("NOMBRE PRODUCTO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO ORDEN");
        jTableMiBitacora.setModel(modelo);
        String[] datos = new String[5];

        objCBD.realizarConexion();
        ArrayList instruccionBD = new ArrayList();
        instruccionBD.add("{call sp_consultarMisOrdenesRealizadas(?)}");
        instruccionBD.add(texto);
        ResultSet cdr = objCBD.ejecutarConsulta(instruccionBD);
        try {
            while (cdr.next()) {
                datos[0] = cdr.getString("id_ordenC");
                datos[1] = cdr.getString("nombre_cliente_llamada");
                datos[2] = cdr.getString("nombreP");
                datos[3] = cdr.getString("cantidad");
                datos[4] = cdr.getString("precioOrden");

                modelo.addRow(datos);
            }
            jTableMiBitacora.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la consulta" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {

            objCBD.cerrarConexion();
        }

    }
}
